SELECT * FROM trans;

BEGIN TRANSACTION;
    INSERT INTO trans SELECT 3 , 'Trans 3';

    INSERT INTO trans SELECT 4 , 'Trans 4';
COMMIT

SELECT * FROM trans;

BEGIN TRANSACTION;
    INSERT INTO trans SELECT 5 , 'Trans 5';

    INSERT INTO trans SELECT 6 , 'Trans 6';
ROLLBACK
